language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t estaton/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true estaton/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2" # http://docker-env.eba-ethqtptw.us-east-2.elasticbeanstalk.com/
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-482265229510"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
