sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t estaton/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true estaton/docker-react npm run test